export default [
  {
    id: "1",
    title: "Hull",
    name: "Hull",
    author: "Buizerd",
    mode: "dodgeball",
    enabled: "1",
    version: "0.1.99",
  },
  {
    id: "2",
    title: "Igloo",
    name: "Igloo",
    author: "Buizerd",
    mode: "dodgeball",
    enabled: "1",
    version: "0.1.99",
  },
  {
    id: "3",
    title: "Temple",
    name: "Temple",
    author: "Buizerd",
    mode: "dodgeball",
    enabled: "1",
    version: "0.1.99",
  },
  {
    id: "4",
    title: "DragonsDen",
    name: "DragonsDen",
    author: "Buizerd",
    mode: "dodgeball",
    enabled: "1",
    version: "0.1.99",
  },
  {
    id: "5",
    title: "dm_Arena1",
    name: "dm_Arena1",
    author: "Buizerd",
    mode: "deathmatch",
    enabled: "1",
    version: "0.1.99",
  },
  {
    id: "6",
    title: "Elysium",
    name: "Elysium",
    author: "Buizerd",
    mode: "captureTheFlag",
    enabled: "1",
    version: "0.1.99",
  },
  {
    id: "7",
    title: "Tobruk",
    name: "Tobruk",
    author: "Buizerd",
    mode: "captureTheFlag",
    enabled: "1",
    version: "0.1.99",
  },
  {
    id: "8",
    title: "ColdFusion",
    name: "ColdFusion",
    author: "Buizerd",
    mode: "captureTheFlag",
    enabled: "1",
    version: "0.1.99",
  },
  {
    id: "9",
    title: "Twin Faces",
    name: "Twin Faces",
    author: "Buizerd",
    mode: "captureTheFlag",
    enabled: "1",
    version: "0.1.99",
  },
  {
    id: "10",
    title: "KodysIsland",
    name: "KodysIsland",
    author: "Buizerd",
    mode: "captureTheFlag",
    enabled: "1",
    version: "0.1.99",
  },
  {
    id: "11",
    title: "Canyon",
    name: "Canyon",
    author: "Buizerd",
    mode: "captureTheFlag",
    enabled: "1",
    version: "0.1.99",
  },
  {
    id: "12",
    title: "Hill364",
    name: "Hill364",
    author: "Buizerd",
    mode: "captureTheFlag",
    enabled: "1",
    version: "0.1.99",
  },
  {
    id: "13",
    title: "Stasis",
    name: "Stasis",
    author: "p0ppin Fresh",
    mode: "captureTheFlag",
    enabled: "1",
    version: "0.1.99",
  },
  {
    id: "14",
    title: "ctf_Evening",
    name: "ctf_Evening",
    author: "Buizerd",
    mode: "captureTheFlag",
    enabled: "1",
    version: "0.1.99",
  },
  {
    id: "15",
    title: "ArcticDusk",
    name: "ArcticDusk",
    author: "Buizerd",
    mode: "captureTheFlag",
    enabled: "1",
    version: "0.1.99",
  },
  {
    id: "16",
    title: "Cathedral",
    name: "Cathedral",
    author: "Buizerd",
    mode: "captureTheFlag",
    enabled: "1",
    version: "0.1.99",
  },
  {
    id: "17",
    title: "ctf_Lambda",
    name: "ctf_Lambda",
    author: "Buizerd",
    mode: "captureTheFlag",
    enabled: "1",
    version: "0.1.99",
  },
  {
    id: "18",
    title: "Aerial",
    name: "Aerial",
    author: "Buizerd",
    mode: "captureTheFlag",
    enabled: "1",
    version: "0.1.99",
  },
  {
    id: "19",
    title: "ctf_FacingWorlds",
    name: "ctf_FacingWorlds",
    author: "Buizerd",
    mode: "captureTheFlag",
    enabled: "1",
    version: "0.1.99",
  },
  {
    id: "20",
    title: "ctf_Ash",
    name: "ctf_Ash",
    author: "Chakapoko Maker",
    mode: "captureTheFlag",
    enabled: "1",
    version: "0.1.99",
  },
  {
    id: "21",
    title: "ctf_Naom",
    name: "ctf_Naom",
    author: "The_Skull",
    mode: "captureTheFlag",
    enabled: "1",
    version: "0.1.99",
  },
  {
    id: "22",
    title: "dm_Hunter",
    name: "dm_Hunter",
    author: "Buizerd",
    mode: "deathmatch",
    enabled: "1",
    version: "0.1.99",
  },
  {
    id: "23",
    title: "Tribal",
    name: "Tribal",
    author: "Buizerd",
    mode: "captureTheFlag",
    enabled: "1",
    version: "0.1.99",
  },
  {
    id: "24",
    title: "Kiwi",
    name: "Kiwi",
    author: "Buizerd",
    mode: "captureTheFlag",
    enabled: "1",
    version: "0.1.99",
  },
  {
    id: "26",
    title: "Webb",
    name: "Webb",
    author: "Buizerd",
    mode: "captureTheFlag",
    enabled: "1",
    version: "0.1.99",
  },
  {
    id: "27",
    title: "dm_Sleet",
    name: "dm_Sleet",
    author: "Dishy",
    mode: "deathmatch",
    enabled: "1",
    version: "0.2.0",
  },
  {
    id: "28",
    title: "SpaceStation",
    name: "SpaceStation",
    author: "M-A-M-A",
    mode: "captureTheFlag",
    enabled: "1",
    version: "0.2.0",
  },
  {
    id: "29",
    title: "Sinkhole",
    name: "Sinkhole",
    author: "Rens Rongen",
    mode: "captureTheFlag",
    enabled: "1",
    version: "0.2.0",
  },
  {
    id: "30",
    title: "LonelyIsland",
    name: "LonelyIsland",
    author: "Rens Rongen",
    mode: "captureTheFlag",
    enabled: "1",
    version: "0.2.0",
  },
  {
    id: "31",
    title: "dm_Nexus",
    name: "dm_Nexus",
    author: "Rens Rongen",
    mode: "deathmatch",
    enabled: "1",
    version: "0.2.0",
  },
  {
    id: "32",
    title: "Arrival",
    name: "Arrival",
    author: "Rens Rongen",
    mode: "training",
    enabled: "1",
    version: "0.3.0",
  },
  {
    id: "33",
    title: "Cavern",
    name: "Cavern",
    author: "Rens Rongen",
    mode: "captureTheFlag",
    enabled: "1",
    version: "0.3.1",
  },
  {
    id: "34",
    title: "dm_Neon",
    name: "dm_Neon",
    author: "Rens Rongen",
    mode: "deathmatch",
    enabled: "1",
    version: "0.3.1",
  },
];
